name: Study Center
favicon: null
layout_spectrum: 0.6774319719988853
typography_spectrum: 0.07966559659689665
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.2917194983456284
  lightness: 0.6889672267716378
  saturation: 0.11638883268460631
  rhythmicContrast: 0.4990327402483672
purpose: []
